---
title: "MARS"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = T, message = FALSE, results='hide', warning=FALSE}
library(caret)
library(tidymodels)
library(splines)
library(mgcv)
library(pdp)
library(earth)
library(tidyverse)
library(ggplot2)
```

# Dataset split
Randomly split dataset into traning (80%) and testing data (20%).
```{r}
# remove id
data <- subset(dat, select = -id)

# set study A/B to 0/1
data$study <- ifelse(data$study == "A", 0, 1)


set.seed(666)
data_split <- initial_split(data, prop = 0.8)

# training data
training_data <- training(data_split)

# test data
testing_data <- testing(data_split)

# matrix of predictors
x <- model.matrix(recovery_time ~ ., training_data) [ ,-1]
y <- training_data$recovery_time
```

Train a multivariate adaptive regression spline (MARS) model.
```{r}
mars_grid <- expand.grid(degree = 1:4, 
                         nprune = 2:38)

ctrl1 <- trainControl(method = "cv", number = 10)

set.seed(666)
mars.fit <- train(x, y,
                  method = "earth",
                  tuneGrid = mars_grid,
                  trControl = ctrl1)

ggplot(mars.fit)

mars.fit$bestTune

coef(mars.fit$finalModel) 

```
The regression function is f(x) = 


The test error is 279.0367.
```{r}
# prediction
mars.pred <- predict(mars.fit, newdata = testing_data)
#test error
mean((mars.pred - testing_data[, "recovery_time"])^2)
```

